import { useState } from 'react';
import './App.css';
import data from './components/Item_Product/data.js';
import ItemProduct from './components/Item_Product/index.jsx';


function App() {
  if(data.length === 0){
    return <h2>No hay productos</h2>
  }

  return (
    <> 
      <main>
        <h2>Welcome to React</h2>
        <section id="container-product">
          <ItemProduct title={data[0].title} description={data[0].description}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[1]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/><ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
          <ItemProduct {...data[0]}/>
        </section>
      </main>
    </>
  )
}

export default App;